common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('daham.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
]

daham/urls.py
from django.conf.urls.static import static
from django.urls import path

from config import settings
from . import views

app_name = 'daham'

urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
    path('board/', views.board, name='board'),
    path('board/<int:board_id>/', views.detail, name='detail'),
    path('board/create/', views.board_create, name='board_create'),
    path('board/update/<int:board_id>/', views.board_update, name='board_update'),
    path('board/delete/<int:board_id>/', views.board_delete, name='board_delete'),
    path('board/<int:board_id>/comment/create/', views.comment_create, name='comment_create'),
    path('board/<int:board_id>/application/create/', views.application_create, name='application_create'),
    path('application/delete/<int:application_id>/', views.application_delete, name='application_delete'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('mypage/', views.mypage, name='mypage'),
    path('profile/', views.profile, name='profile'),
    # 함께할래요
    path('want_board/', views.want_board, name='want_board'),
    path('want_board/<int:board_id>/', views.want_board_detail, name='want_board_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
<body>

{% include "navbar.html" %}

{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}    <!-- 필드 오류 (형식) -->
            <div class="alert alert-success">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}    <!-- 넌필드 오류(입력값과 관계 없음) -->
        <div class="alert alert-success">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- 네비게이션바 -->
<nav class="nav">
    <a class="navbar-brand" href="{% url 'daham:index' %}"> <img src="{% static 'img/logo2.png' %}" alt=""/> </a>
    {% if user.is_authenticated %}
        <ul class="menu navbar">
            <li class="nav-item">
                <a href="{% url 'daham:intro' %}">다함개</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'daham:board' %}">함께하기</a>   <!-- 봉사 신청 -->
            </li>
            <li class="nav-item">
                <a href="{% url 'daham:want_board' %}">함께할래요</a>   <!-- 내가 쓴 글에 봉사 신청한 사람 목록 -->
            </li>
        </ul>
        <ul class="user navbar">
            <li class="nav-item">
                <a href="{% url 'daham:mypage' %}"><span>{{ user.username }}님</span></a>
            </li>&nbsp;&nbsp;&nbsp;&nbsp;
            <li class="nav-item">
                <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
            </li>
        </ul>
    {% else %}
        <ul class="menu navbar">
            <li class="nav-item">
                <a href="{% url 'common:login' %}">다함개</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'common:login' %}">함께하기</a>   <!-- 봉사 신청 -->
            </li>
            <li class="nav-item">
                <a href="{% url 'common:login' %}">함께할래요</a>   <!-- 내가 쓴 글에 봉사 신청한 사람 목록 -->
            </li>
        </ul>
        <ul class="user navbar">
            <li class="nav-item">
                <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
            </li>&nbsp;&nbsp;&nbsp;&nbsp;
            <li class="nav-item">
                <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
            </li>
        </ul>
    {% endif %}
    {#    </div>#}
</nav>