common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('daham.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
]

daham/urls.py
from django.conf.urls.static import static
from django.urls import path

from config import settings
from . import views

app_name = 'daham'

urlpatterns = [
    path('', views.index, name='index'),
    path('intro/', views.intro, name='intro'),
    path('board/', views.board, name='board'),
    path('board/<int:board_id>/', views.detail, name='detail'),
    path('board/create/', views.board_create, name='board_create'),
    path('board/update/<int:board_id>/', views.board_update, name='board_update'),
    path('board/delete/<int:board_id>/', views.board_delete, name='board_delete'),
    path('board/<int:board_id>/comment/create/', views.comment_create, name='comment_create'),
    path('board/<int:board_id>/application/create/', views.application_create, name='application_create'),
    path('application/delete/<int:application_id>/', views.application_delete, name='application_delete'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('mypage/', views.mypage, name='mypage'),
    path('profile/', views.profile, name='profile'),
    # 함께할래요
    path('want_board/', views.want_board, name='want_board'),
    path('want_board/<int:board_id>/', views.want_board_detail, name='want_board_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daham/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models


# 유저와 1:1 연결, 이미지, 한줄소개 저장하기 위해
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 1:1로 연결
    nickname = models.CharField(max_length=40, blank=True)
    description = models.TextField(blank=True)
    image = models.ImageField(blank=True)


class Board(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    content = models.TextField()
    image = models.ImageField(blank=True, upload_to="images/", null=True)
    end_date = models.DateField(null=True)  #봉사 날짜
    created_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(auto_now_add=True)


class Application(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저
    created_date = models.DateTimeField(auto_now_add=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from daham.models import Profile


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    nickname = forms.CharField(label='닉네임')

    class Meta:
        model = User
        fields = ("username", "email")

    def save(self):
        user = super().save()
        new_profile = Profile.objects.create(
            user=user,
            nickname=self.cleaned_data.get('nickname'),  # self.cleaned_data['nickname']
        )
        return new_profile


# class LoginForm(forms.ModelForm):
#     password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
#
#     class Meta:
#         model = User
#         fields = ['username', 'password']

daham/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm

from daham.models import Board, Comment, Profile


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'description', 'image']


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content', 'image', 'end_date']

        widgets = {
            'end_date': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답글'
        }

daham/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

now = datetime.now()
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from daham.forms import BoardForm, CommentForm, ProfileForm, CustomUserChangeForm
from daham.models import Board, Application, Comment, Profile


def index(request):
    return render(request, 'daham/index.html')


def intro(request):
    return render(request, 'daham/intro.html')


@login_required(login_url='common:login')
def board(request):
    page = request.GET.get('page', '1')
    board_list = Board.objects.order_by('end_date')
    today = datetime.now().date()

    paginator = Paginator(board_list, 8)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'today': today}

    return render(request, 'daham/board_list.html', context)


@login_required(login_url='common:login')
def board_create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES)
        if form.is_valid():
            board = form.save(commit=False)  # commit=Fasle는 아직 임시저장
            user = request.user
            board.profile = Profile.objects.get(user=user)
            board.created_date = timezone.now()  # created_date까지 설정한 후
            board.image = form.cleaned_data['image']
            board.save()  # 진짜 저장
            return redirect('daham:board')
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'daham/board_form.html', context)


def detail(request, board_id):
    board = Board.objects.get(id=board_id)
    user = request.user
    profile = Profile.objects.get(user=user)
    application = Application.objects.filter(board=board, profile=profile)
    context = {'board': board, 'application_list': application}

    return render(request, 'daham/board_detail.html', context)


@login_required(login_url='common:login')
def board_update(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.profile.user:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('daham:detail', board_id=board.id)

    if request.method == "POST":
        form = BoardForm(request.POST, request.FILES, instance=board)  # 기존 값을 폼에 채우기
        if form.is_valid():
            board = form.save(commit=False)
            user = request.user
            profile = Profile.objects.get(user=user)
            board.profile = profile
            board.image = form.cleaned_data['image']
            board.save()
            return redirect('daham:detail', board_id=board.id)
    else:
        form = BoardForm(instance=board)  # 기존 값을 폼에 채우기
    context = {'form': form}
    return render(request, 'daham/board_form.html', context)


@login_required(login_url='common:login')
def board_delete(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.profile.user:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('daham:detail', board_id=board.id)
    board.delete()
    return redirect('daham:board')


@login_required(login_url='common:login')
def comment_create(request, board_id):
    board = get_object_or_404(Board, pk=board_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            user = request.user
            comment.profile = Profile.objects.get(user=user)
            comment.board = board
            comment.save()
            return redirect('daham:detail', board_id=board.id)
    else:
        form = CommentForm()
    context = {'board': board, 'form': form}
    return render(request, 'daham/board_detail.html', context)


@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.profile.user:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('daham:detail', board_id=comment.board.id)
    comment.delete()
    return redirect('daham:detail', board_id=comment.board.id)


def application_create(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    user = request.user
    profile = Profile.objects.get(user=user)
    Application.objects.create(board=board, profile=profile, created_date=timezone.now())
    board.save()

    return redirect('daham:detail', board_id=board_id)


def application_delete(request, application_id):
    application = get_object_or_404(Application, pk=application_id)
    if request.user != application.profile.user:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('daham:detail', board_id=application.board.id)
    application.delete()
    return redirect('daham:detail', board_id=application.board.id)


@login_required(login_url='common:login')
# 유저 프로필
def mypage(request):
    page = request.GET.get('page', '1')
    user = request.user
    profile = Profile.objects.get(user=user)
    today = datetime.now().date()

    application_board = Application.objects.all().filter(profile=profile)
    paginator = Paginator(application_board, 2)
    page_obj = paginator.get_page(page)

    context = {'person': profile, 'board_list': page_obj, 'today': today}

    return render(request, 'daham/mypage.html', context)


@login_required(login_url='common:login')
@method_decorator(csrf_exempt)
def profile(request):
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect('daham:mypage')
        return redirect('daham:profile')
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        profile, create = Profile.objects.get_or_create(user=request.user)
        profile_form = ProfileForm(instance=profile)
        return render(request, 'daham/profile_form.html',
                      {'user_change_form': user_change_form, 'profile_form': profile_form})


# 함께할래요
@login_required(login_url='common:login')
def want_board(request):
    page = request.GET.get('page', '1')
    profile = Profile.objects.get(user=request.user)
    board_list = Board.objects.filter(profile=profile).order_by('end_date')
    today = datetime.now().date()

    paginator = Paginator(board_list, 4)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'today': today}

    return render(request, 'daham/want_board_list.html', context)


def want_board_detail(request, board_id):
    page = request.GET.get('page', '1')
    board = Board.objects.get(id=board_id)

    application_list = Application.objects.filter(board=board)
    paginator = Paginator(application_list, 5)
    page_obj = paginator.get_page(page)

    return render(request, 'daham/want_board_detail.html', {'application_list': page_obj})

templates/daham/board_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}상세보기{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board_detail.css' %}">
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul>
                    <li>{{ message.message }}</li>
                </ul>
            {% endfor %}
        </div>
    {% endif %}

    <div class="detail-con">
        <div class="header">
            <div class="user-info">
                <img {% if board.profile.image %} src="{{ board.profile.image.url }}"
                                                   {% else %}src="https://i.stack.imgur.com/34AD2.jpg"{% endif %}
                                                   class="user-img" alt="">
                <div class="user-more-info">
                    <h1>{{ board.profile.nickname }}</h1>
                    <h6>{{ board.created_date }}</h6>
                </div>
            </div>
            <div class="board-info">
                <div class="comments">
                    <span>댓글</span>
                    <h3>{{ board.comment_set.all.count }}</h3>
                </div>
                <div class="applications">
                    <span>신청수</span>
                    <h3>{{ board.application_set.all.count }}</h3>
                </div>
            </div>
        </div>
        <div class="detail-content">
            <div class="import-info">
                <h1>{{ board.title }}</h1>
                <div class="btn-group">
                    {% if board.profile.user != request.user %}
                        {% if application_list.count == 0 %}
                            <a href="{% url 'daham:application_create' board.id %}">
                                <button>신청하기</button>
                            </a>
                        {% else %}
                            {% for application in application_list.all %}
                                <a href="{% url 'daham:application_delete' application.id %}">
                                    <button>신청취소</button>
                                </a>
                            {% endfor %}
                        {% endif %}
                    {% else %}
                    {% endif %}

                    {% if request.user == board.profile.user %}
                        <a href="{% url 'daham:board_update' board.id %}">
                            <button><i class="fas fa-pencil-alt"></i></button>
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="#" class="delete" data-uri="{% url 'daham:board_delete' board.id %}">
                            <button style="color:red;"><i class="far fa-trash-alt"></i></button>
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="contents">
                <div class="end_date">
                    <h3>봉사일</h3>
                    <h5>{{ board.end_date }}</h5>
                </div>
                <h4>{{ board.content }}</h4>
                {% if board.image %}
                    <img src="{{ board.image.url }}" class="board-img" alt="">
                {% endif %}
            </div>
        </div>
        <div class="comment-con">

            {% for comment in board.comment_set.all %}
                <div class="comment-info">
                    <div class="info one">
                        <div class="one-one">
                            <h5>{{ comment.profile.nickname }}</h5>
                            <h6>{{ comment.created_date|date:'Y-m-d' }}</h6>
                        </div>
                    </div>
                    <div class="info second">
                        <h5>{{ comment.content }}</h5>
                        {% if request.user == comment.profile.user %}
                            <a href="#" class="delete" data-uri="{% url 'daham:comment_delete' comment.id %}">
                                <button class="btn-com"><i class="far fa-trash-alt"></i></button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

            <form action="{% url 'daham:comment_create' board.id %}" method="post">
                {% csrf_token %}
                <input {% if not user.is_authenticated %}disabled{% endif %} name="content" class="in-com"
                       placeholder="댓글을 입력해주세요" autocomplete="off" id="content">
                <button type="submit" class="submit"><img src="{% static 'img/send.png' %}" alt=""/></button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".delete").on('click', function () {
                if (confirm("정말 삭제하시겠습니까?")) {
                    location.href = $(this).data('uri');
                }
            });
        });
    </script>
{% endblock %}

templates/daham/board_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}글 목록{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board_list.css' %}">
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
{% endblock %}

{% block content %}
    <a href="{% url 'daham:board_create' %}" class="btn-lg btn-create"><i class="fas fa-plus"></i>&nbsp;&nbsp;글 등록</a>
    {% if board_list %}
        <div class="board-con">
            {% for board in board_list %}
                <a href="{% url 'daham:detail' board.id %}">
                    <div class="board">
                        {% if board.image %}
                            <img src="{{ board.image.url }}" class="board-img" alt="">
                        {% else %}
                            <img src="{% static 'img/defaultImg.png' %}" class="board-img" alt="">
                        {% endif %}
                        <div class="board-info">
                            <span class="board-title">{{ board.title }}</span>
                            {% if today == board.end_date %}
                                <span class="end-date" style="color:red">{{ board.end_date }}</span>
                            {% else %}
                                <span class="end-date">{{ board.end_date }}</span>
                            {% endif %}
                        </div>
                        <div class="board-info second">
                            <span>{{ board.profile.nickname }}</span>
                            <div class="board-more-info">
                                <i class="fas fa-comment"></i>&nbsp;{{ board.comment_set.all.count }}&nbsp;&nbsp;
                                <i class="fas fa-address-book"></i>&nbsp;{{ board.application_set.all.count }}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if board_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ border_list.previous_page_number }}">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}

            <!-- 페이지리스트 -->
            {% for page_number in board_list.paginator.page_range %}
                {% if page_number >= board_list.number|add:-4 and page_number <= board_list.number|add:4 %}
                    {% if page_number == board_list.number %}
                        <li class="page-item active page-cur" aria-current="page">
                            <a class="page-link" href="?page{{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item page-cur">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            <!-- 다음페이지 -->
            {% if board_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ board_list.next_page_number }}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

templates/daham/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}다함개{% endblock %}

{% block content %}
    <div class="con">
        <video muted autoplay loop>
            <source src="{% static 'img/video5.mp4' %}" type="video/mp4"/>
        </video>
        <div class="background_box"></div>

        <div class="textcon">
            <h1>다함개</h1>
            <h4>다음에 또 함께하개!</h4>
            <h4>혼자 봉사가기 어렵다면, 함께하자 봉사!</h4>
            {% if user.is_authenticated %}
                <a href="{% url 'daham:board' %}"><button class="sta-btn">시작하기</button></a>
            {% else %}
                <a href="{% url 'common:login' %}"><button class="sta-btn">시작하기</button></a>
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/daham/profile_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/profile_form.css' %}">
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">회원정보 변경</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% if form.errors %}
                <div role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            <input type="hidden" name="csrfmiddlewaretoken"
                   value="gZqCdZsuztGYUOU3ANj6CFye4VSda7axElbqnzgSiLjhB35waq7gBIYdmv6krbWd">


            <div class="form-group"><label for="id_username">사용자 이름</label>
                <input type="text" name="username"
                       value="{{ user_change_form.username.value|default_if_none:'' }}" maxlength="150"
                       class="form-control"
                       autocomplete="off"
                       style="font-weight: bold; color: gray"
                       placeholder="사용자 이름"
                       title="150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다."
                       required="" id="id_username">
                <small class="form-text text-muted">150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.</small>
            </div>
            <div class="form-group"><label for="id_email">이메일 주소</label>
                <input type="email" name="email"
                       value="{{ user_change_form.email.value|default_if_none:'' }}"
                       maxlength="254"
                       class="form-control"
                       autocomplete="off"
                       placeholder="이메일 주소" title=""
                       id="id_email"></div>
            <div class="form-group"><label for="id_nickname">닉네임</label>
                <input type="text" name="nickname"
                       value="{{ profile_form.nickname.value|default_if_none:'' }}" maxlength="40"
                       class="form-control"
                       placeholder="닉네임"
                       autocomplete="off"
                       title="" id="id_nickname">
            </div>
            <div class="form-group">
                <label for="id_description">한줄 소개</label>
                <textarea name="description" cols="40" rows="10" class="form-control"
                          placeholder="자신을 표현할 수 있는 한 줄 소개를 적어주세요!" id="id_description">{{ profile_form.description.value}}</textarea>
            </div>
            <div class="form-group">
                <div class="fileBox">
                    <label for="image" class="btn_file"><img src="{% static 'img/image.png' %}" alt=""/></label>
                    <input type="text" class="fileName" readonly="readonly">
                    <input type="file" id="image" value="{{ profile_form.image.url|default_if_none:'' }}" name="image"
                           accept="image/*" class="uploadBtn">
                </div>
            </div>
            <button type="submit" class="submit">등록</button>
        </form>
    </div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        var uploadFile = $('.fileBox .uploadBtn');
        uploadFile.on('change', function () {
            if (window.FileReader) {
                var filename = $(this)[0].files[0].name;
            } else {
                var filename = $(this).val().split('/').pop().split('\\').pop();
            }
            $(this).siblings('.fileName').val(filename);
        });
    </script>
{% endblock %}

templates/daham/want_board_list.html
{% extends 'base.html' %}
{% block title %}함께할래요{% endblock %}

{% load static %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/board_list.css' %}">
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
{% endblock %}

{% block content %}
    <h2 style="text-align: center; font-weight: bold">내가 작성한 글</h2>

    {% if board_list %}
        <div class="board-con" style="padding: 80px 90px 100px 130px;">
            {% for board in board_list %}
                <a href="{% url 'daham:want_board_detail' board.id %}">
                    <div class="board">
                        {% if board.image %}
                            <img src="{{ board.image.url }}" class="board-img" alt="">
                        {% else %}
                            <img src="{% static 'img/defaultImg.png' %}" class="board-img" alt="">
                        {% endif %}
                        <div class="board-info">
                            <span class="board-title">{{ board.title }}</span>
                            {% if today == board.end_date %}
                                <span class="end-date" style="color:red">{{ board.end_date }}</span>
                            {% else %}
                                <span class="end-date">{{ board.end_date }}</span>
                            {% endif %}
                        </div>
                        <div class="board-info second">
                            <span>{{ board.profile.nickname }}</span>
                            <div class="board-more-info">
                                <i class="fas fa-comment"></i>&nbsp;{{ board.comment_set.all.count }}&nbsp;&nbsp;
                                <i class="fas fa-address-book"></i>&nbsp;{{ board.application_set.all.count }}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if board_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ border_list.previous_page_number }}">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}

            <!-- 페이지리스트 -->
            {% for page_number in board_list.paginator.page_range %}
                {% if page_number >= board_list.number|add:-4 and page_number <= board_list.number|add:4 %}
                    {% if page_number == board_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page{{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            <!-- 다음페이지 -->
            {% if board_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ board_list.next_page_number }}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>
    {% else %}
        <div class="concon">
            <h3 style="font-weight: bold; margin-top: 30px;">아직 작성한 글이 없습니다. 서둘러 글을 작성해보세요 ! 😎</h3>
            <a href="{% url 'daham:board_create' %}" class="btn-lg btn-wcreate"><i class="fas fa-plus"></i>&nbsp;&nbsp;글 등록 하기</a>
        </div>

    {% endif %}


{% endblock %}